#!/bin/bash

GITHUB_FOLDER="$1"  # URL of the GitHub folder to download files from
FILE_EXTENSION="$2" # File extension to filter

# Fetch and process file URLs
fetch_file_urls() {
    curl --silent "$GITHUB_FOLDER" | \
    grep --only-matching --perl-regexp 'href="/\K[^"]+\.'"${FILE_EXTENSION}"'' | \
    sed -e 's/^/https:\/\/raw.githubusercontent.com\//' -e 's/blob\///' | \
    uniq
}

# Download files
download_files() {
    local files=$(fetch_file_urls)
    
    for link in $files; do
        echo "Downloading $(basename "$link")"
        curl --remote-name "$link"
    done
}

# Main execution
main() {
    if [ $# -ne 2 ]; then
        echo "Usage: $0 <github_folder_url> <file_extension>"
        exit 1
    fi
    
    download_files;
}

main "$@"
